export enum EstadoCita {
  BLOQUEO_TEMPORAL = 'BLOQUEO_TEMPORAL',
  PRE_AGENDADA = 'PRE_AGENDADA',
  EN_REVISION = 'EN_REVISION',
  CONFIRMADA = 'CONFIRMADA',
  REAGENDADA = 'REAGENDADA',
  CANCELADA = 'CANCELADA',
  CANCELADA_SISTEMA = 'CANCELADA_SISTEMA',
  COMPLETADA = 'COMPLETADA',
  NO_ASISTIO = 'NO_ASISTIO',
}

export enum EstadoPago {
  PENDIENTE = 'PENDIENTE',
  REVISION = 'REVISION',
  APROBADO = 'APROBADO',
  RECHAZADO = 'RECHAZADO',
  REEMBOLSADO = 'REEMBOLSADO',
}

export enum MetodoPago {
  NEQUI = 'NEQUI',
  DAVIPLATA = 'DAVIPLATA',
  TARJETA = 'TARJETA',
  SISTECREDITO = 'SISTECREDITO',
  EFECTIVO = 'EFECTIVO',
}
